### ISSUE TITLE
Video thumbnails displaying extremely large size

### ISSUE THREAD

**Issue by bmhieserich** [Tubefeeder/Tubefeeder#127]
After today's update to the flatpak version, thumbnails appear in an extremely large size, with some pushing the size of the window beyond the screen resolution. An example image is shown below.

![Screenshot_20230415_205452](https://user-images.githubusercontent.com/108948388/232261990-5cc0df34-8572-4be9-92c0-d401c3c29a80.png)

On OpenSUSE Tumbleweed, screen resolution 1920x1080

**Comment by Schmiddiii** [comment]
Yes, I also noticed. Sorry for that, I will release a hotfix update fixing this today.
