### ISSUE TITLE
Weblate

### ISSUE THREAD

**Issue by vikdevelop** [Tubefeeder/Tubefeeder#132]
Wouldn't it be better to use Hosted Weblate instead of Github pull request to translate the application?

**Comment by Schmiddiii** [comment]
I agree hat Weblate is quite nice for translation. Sadly (as I think I already mentioned in a PR or issue), I already have a project with the Libre-tier (which only includes a maximum of one project) of Weblate, [Flare](https://hosted.weblate.org/projects/flare/) (note that this runs from my GitLab account and I theoretically could make a separate account from this GitHub account, but that would be pretty much cheating and not nice). And upgrading to a plan that allows for at least two projects (the medium plan) would already be 500€ per year, way more than I would be ready to pay.
