### ISSUE TITLE
Error Parsing All LBRY Subscriptions

### ISSUE THREAD

**Issue by bmhieserich** [Tubefeeder/Tubefeeder#134]
None of my LBRY/Odysee subscriptions are pulling in on any Piped API instance. "Error parsing subscriptions" appears at the top. Looking at the Odysee website, it appears that there was a UI update/overhaul that I would guess corresponded with API changes or something similar which is preventing subscriptions from being parsed/pulled. If nothing else, just making devs aware so that adjustments can be made if/when you can.

**Comment by Schmiddiii** [comment]
Works fine for me with:

- `@AlphaNerd:8`
- `@Distrotube:2`

Could you share subscriptions that are broken for you? Did you maybe add the subscription in the wrong format?

**Comment by bmhieserich** [comment]
It looks like it was fixed overnight. Thanks for taking a look into it anyway!
