### ISSUE TITLE
Sync subscriptions with Piped

### ISSUE THREAD

**Issue by julianfairfax** [Tubefeeder/Tubefeeder#140]
Piped lets you log into an account to sync subscriptions. It would be nice if Tubefeeder supported this!

I can't really see myself continuing to use it otherwise, as it would not make sense to export them from the Piped website every time there's a change.

**Comment by Schmiddiii** [comment]
I feel like this is out of the scope of Tubefeeder.

Furthermore, I don't think there is currently an API for getting the subscriptions from Piped. And if there really was such an API, it would be pretty easy to create a script that automatically updates the Tubefeeder subscription file from the Piped subscription.
