### ISSUE TITLE
Need a way to copy a link to video.

### ISSUE THREAD

**Issue by VovaFreeman** [Tubefeeder/Tubefeeder#33]
It'll greatly improve number of usecases if there will be a way to copy video links in the feed or/and watchlist. Some kind of a button or a long press to copy to clipboard on pinephone.

**Comment by Schmiddiii** [comment]
This seems possible to do. I will probably implement this directly in the refactoring-branch, so it will still take a while.

**Comment by Schmiddiii** [comment]
This is now available on flathub-beta and seems to be working on the PinePhone. Feel free to test it out.

To copy the url of the video, click on the new button left of the "watch-later" button, then click on the clipboard.
