### ISSUE TITLE
Error parsing N subscriptions (N is ~10% of the total list)

### ISSUE THREAD

**Issue by VovaFreeman** [Tubefeeder/Tubefeeder#49]
Tubefeeder constantly shows the Error message at the top of the window. About 10% of my ~300 subscriptions are not parsed. What information or logs can I provide to investigate this?

OS: Manjaro/Posh;
Build: On pinephone natively from latest source; 
Start: From terminal Tubefeeder-1.6.2/target/release/tubefeeder;
STDERR: ERROR tf_platform_youtube::subscription  Error generating youtube videos from subscription IDofAChannelHere;

The list was imported to csv file with bash. Double checked row entries and channels - all are working well in a browser or as separate entries.

**Comment by Schmiddiii** [comment]
I will need a little more information:

- Is the `N` varying or always the same number?
- Can you provide a more detailed log using `RUST_LOG=trace cargo run` in your terminal (or similar). I will not need everything, the main interest is probably the lines above the error you mentioned.
- At least one youtube ID where this failed would be nice if always the same channels fail.
- Do you see the correct subscriptions (including names) in the subscription list? Do some subscriptions have their ID instead of their names (it will take a few moments before the names will be filled out, so please wait a while there)

**Comment by VovaFreeman** [comment]
- N is a constant for a day with constant playlist. (If a single subscription added/changed/deleted the whole picture changes: Number of unresolved channels and those  channels);

- [RUST_LOG](https://gist.github.com/c60d96915745fed6ece5cc285499bb7c)

- Every 6th or 7th channel are not resolved (shown as IDs) but this is not consistent through a whole list. (sometimes its 2 together and 10 resolved after it). Most of the time there's a message at the top: "Error connecting to the network". But my pinephone is constantly connected to a 4G cellular network.

- For example 10 unresolved IDs (for today with my main playlist):
UC2_mG3h-AxxK2oz08j2bz2g
UC4HgnAtfzjyUhYV83jBe3Kg
UC5ZsENSXOVzI0zHt4i2bZFw 
UC7Awuu4OccGePAeQlwtI1Yg
UCCj7k6twL9MD9-fVU__Rk5A
UCDqHUzLZmlESwpoJ6-1bxaQ
UCEhBM2x5MG9-e_JSOzU068w
UCFpGp4hHe03nvF9c8_gF_jA
UCFsZ2CadKpAt_yInoTcVRnQ
UCFxiUzeQ6ZPtnzZpUyNj9jw;

- Yes. All other channels are resolved (shown as Names) in the subscriptions tab and their new videos are shown in the feed if there are any.

**Comment by Schmiddiii** [comment]
I already see a few problematic channels on your subscription list (from the log):

- You query a channel with id `Channel {` [here](https://gist.github.com/VovaFreeman/c60d96915745fed6ece5cc285499bb7c#file-errorsout-txt-L455). Probably a error in the bash script of converstion.
- The channel `The Silenced` with ID `UCOeX05Mko7ffxOl3Gg85NeA` seems to have been deleted. It should still be possible to parse this, so this is a bug.

Other channels seem fine, I still have to investigate it a little bit closer. I already found some `null` values where there should be none.

**Comment by Schmiddiii** [comment]
I have fixed the parsing errors of (as far as I checked) all but the above mentioned problematic ones and made a PR to a upstream library used. As soon as this will be merged and a new version is released, I am going to publish a new version of Tubefeeder that should fix this issue. Thank you for your detailed logs.

**Comment by Schmiddiii** [comment]
A new version should be published to Flathub in a few hours. Please try if this fixed all issues and reopen otherwise.
