### ISSUE TITLE
Crashes when system has unsupported locale 

### ISSUE THREAD

**Issue by TrygveN** [Tubefeeder/Tubefeeder#53]
I have my language set to Norwegian which which makes the application not launch and print this error:
`thread 'main' panicked at 'Failed to initialize internationalization: TranslationNotFound("nb")', src/main.rs:64:33`
It seems like there is no fallback to English when the pot file is not found.

**Comment by Schmiddiii** [comment]
I really thought I checked this when implementing internationalization. But this should probably be a pretty easy fix. Already working on it.

**Comment by Schmiddiii** [comment]
Should now be fixed on master branch. WIll update the flatpak, but this will take a few hours.

**Comment by Schmiddiii** [comment]
The flatpak should now be updated on flathub. Please test it and reopen the issue if it is still not resolved.

**Comment by TrygveN** [comment]
It works correctly now. This was really fast!
