### ISSUE TITLE
Feeds won't load on Flatpak v1.6.4

### ISSUE THREAD

**Issue by jg110** [Tubefeeder/Tubefeeder#56]
Using the version 1.6.4 Flatpak, the feeds screen is blank, and pressing the reload button results in it trying to load for about half a second before giving up without loading anything.

**Comment by jg110** [comment]
Never mind, I just realized you have to add subscriptions first before anything shows up in the feed. If this info is in the wiki, I must have missed it. If not, it would be good to add that.

**Comment by Schmiddiii** [comment]
I thought this would be obvious as I have no intent on showing people videos they are not interested in, e.g. "trending" videos. Therefore, there is no explicit mention about this in the wiki or the homepage, but I would also not know where this would fit.
