### ISSUE TITLE
Import subscriptions from youtube .csv

### ISSUE THREAD

**Issue by daudix-UFO** [Tubefeeder/Tubefeeder#61]

**Comment by Schmiddiii** [comment]
Could you please send a example file? I have not yet seen any such files.

**Comment by daudix-UFO** [comment]
example: 
[subscriptions.csv](https://github.com/Tubefeeder/Tubefeeder/files/8929237/subscriptions.csv)

**Comment by Schmiddiii** [comment]
I have just opened a PR with a small script that would fix this issue. As mentioned in the PR, this will need to be documented, but the basic gist is to execute the script with the `subscriptions.csv` as a argument and save the output in `~/.local/share/tubefeeder/subscriptions.csv`.

Please test it out and report any feedback if something goes wrong.

Please note that the example you sent does not seem to be valid, the first and last lines seem to be cut off in the url and as far as I found the csv has a header your file does not have.

**Comment by daudix-UFO** [comment]
Oh, sorry for broken example, will teat script today ;)

**Comment by daudix-UFO** [comment]
Hi, I have tested this script, and it works!
