### ISSUE TITLE
Adaptive UI for tablet-laptop

### ISSUE THREAD

**Issue by daudix-UFO** [Tubefeeder/Tubefeeder#62]

**Comment by Schmiddiii** [comment]
I think this should already be usable on these devices. What exactly is your problem on tablets/laptops?

**Comment by daudix-UFO** [comment]
Yes, but tabs looks very stretched, in desktop mode, it can be moved to top bar

**Comment by daudix-UFO** [comment]
Example of tabs on top:

![Снимок экрана от 2022-06-17 19-38-01](https://user-images.githubusercontent.com/77155297/174340475-a5a53d9f-374a-4641-974d-09559f77aea1.png)
![Снимок экрана от 2022-06-17 19-37-54](https://user-images.githubusercontent.com/77155297/174340478-fd210d64-169d-4fb6-9662-b0fb99787c1f.png)

**Comment by Schmiddiii** [comment]
This should also be fixed in the new PR. Once you have verified the youtube script I will do a minor release (probably some time tomorrow) with both PRs merged, then you can verify the adaptive view switcher.

**Comment by daudix-UFO** [comment]
Good!

BTW, I working on a new icons, hope will finish before release

**Comment by Schmiddiii** [comment]
You mean new icons for Tubefeeder? Sounds great, I will wait until you finished then. Feel free to just open a PR if you are finished or want to show some icons.

**Comment by daudix-UFO** [comment]
Thank you !
